language: objective-c
osx_image: beta-xcode6.3

script: 
- xctool -workspace Dollar.xcworkspace -scheme Dollar -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test
- xctool -workspace Dollar.xcworkspace -scheme Cent -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test
